# Generated by Django 4.1.2 on 2023-07-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=10),
        ),
    ]
