# Generated by Django 4.1.2 on 2023-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_alter_passport_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
