# Generated by Django 4.1.2 on 2023-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0003_alter_passport_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='gender',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nation',
            field=models.CharField(choices=[('кыргыз', 'Кыргыз'), ('орус', 'Орус'), ('американец', 'Американец')], max_length=15),
        ),
    ]
