# Generated by Django 4.1.2 on 2023-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0004_alter_passport_gender_alter_passport_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='image',
            field=models.ImageField(default=1, upload_to='passport_image'),
            preserve_default=False,
        ),
    ]
