# Generated by Django 4.1.2 on 2023-07-04 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0005_passport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='created_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
