# Generated by Django 4.1.2 on 2023-07-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capital', models.CharField(max_length=150)),
                ('flag', models.ImageField(upload_to='country_flag')),
                ('hymn', models.FileField(upload_to='country_hymn')),
                ('population', models.IntegerField(default=0)),
                ('total_area', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('index', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=150)),
                ('population', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='countries.country')),
            ],
        ),
    ]
